export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_USER: "SET_USER",
    SET_PLAYLISTS: "SET_PLAYLISTS",
    SET_PLAYING: "SET_PLAYING",
    SET_PLAYER_STATE: "SET_PLAYER_STATE",
    SET_PLAYLIST: "SET_PLAYLIST",
    SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
    SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
    SET_PLAYER_STATUS: "SET_PLAYER_STATUS",
    SET_SHUFFLE_STATE: "SET_SHUFFLE_STATE", 
    SET_DEVICE_ID: "SET_DEVICE_ID",   
};